from mcp_tools import (
    current_metric_for_pods_tool,
    workload_metrics_tool,
    top_n_pods_by_metric_tool,
    pod_network_io_tool,
    pods_exceeding_cpu_tool,
    pods_exceeding_memory_tool,
    pod_status_summary_tool,
    recent_pod_events_tool,
    node_disk_usage_tool,
    node_memory_usage_tool,
    top_memory_pressure_nodes_tool,
    describe_cluster_health_tool,
    top_disk_pressure_nodes_tool,
    pod_restart_trend_tool,
    detect_pod_anomalies_tool,
    namespace_resource_summary_tool,
    detect_crashloop_pods_tool,
    correlate_metrics_tool,
    pod_event_timeline_tool,
    node_condition_summary_tool,
)

TOOLS = {
    "current_metric_for_pods":    current_metric_for_pods_tool,
    "workload_metrics":           workload_metrics_tool,
    "top_n_pods_by_metric":       top_n_pods_by_metric_tool,
    "pod_network_io":             pod_network_io_tool,
    "pods_exceeding_cpu":         pods_exceeding_cpu_tool,
    "pods_exceeding_memory":      pods_exceeding_memory_tool,
    "pod_status_summary":         pod_status_summary_tool,
    "recent_pod_events":          recent_pod_events_tool,
    "node_disk_usage":            node_disk_usage_tool,
    "node_memory_usage":          node_memory_usage_tool,
    "top_memory_pressure_nodes":  top_memory_pressure_nodes_tool,
    "describe_cluster_health":    describe_cluster_health_tool,
    "top_disk_pressure_nodes":    top_disk_pressure_nodes_tool,
    "pod_restart_trend":          pod_restart_trend_tool,
    "detect_pod_anomalies":       detect_pod_anomalies_tool,
    "namespace_resource_summary": namespace_resource_summary_tool,
    "detect_crashloop_pods":      detect_crashloop_pods_tool,
    "correlate_metrics":          correlate_metrics_tool,
    "pod_event_timeline":         pod_event_timeline_tool,
    "node_condition_summary":     node_condition_summary_tool,
}
